package dev.ole.netease.channel;

import dev.ole.netease.Available;
import dev.ole.netease.Closeable;
import dev.ole.netease.NetAddress;
import dev.ole.netease.packet.Packet;
import dev.ole.netease.request.RequestProvider;
import io.netty5.channel.Channel;

public interface NetChannel extends Available, Closeable, RequestProvider {

    /**
     * Get the id of the channel.
     * Channel id is unique for each channel
     * The id is generated by the server, if the channel is not connected to the server, the id is null
     * Default -> random uuid -> config can be changed
     * @return id
     */
    String id();

    /**
     * Get the netty channel
     * @return channel
     */
    Channel channel();

    /**
     * Get the client side host information
     * @return NetAddress with port and host
     */
    NetAddress clientAddress();

    /**
     * Send a packet to the server
     * Only if available is ture
     * @param packet to send
     */
    void send(Packet packet);

    /**
     * Update the current client id
     * @param id new id
     */
    void updateId(String id);

}