[versions]

annotations = "26.0.2"
lombok = "1.18.34"
netty5 = "5.0.0.Alpha5"
log4j2 = "2.24.1"
junitBom = "5.10.0"
awaitility = "4.2.2"

[libraries]
lombok = { group = "org.projectlombok", name= "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name= "annotations", version.ref = "annotations" }
netty5 = { group = "io.netty", name = "netty5-all", version.ref = "netty5" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2" }
log4j2-simple = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j2" }


# testing
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitEngine = { group = "org.junit.platform", name = "junit-platform-suite-engine"  }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }

[bundles]
testing = ["junit", "junitEngine", "log4j2-simple", "awaitility"]
utils = ["lombok", "annotations", "log4j2"]
